version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar/22103228:sonartoken
    HOST: prod/sonar/22103228:HOST
    Organization: prod/sonar/22103228:Organization
    Project: prod/sonar/22103228:Project
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - sudo yum update -y
      - yum install -y jq
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
      - tar xzf apache-maven-3.9.5-bin.tar.gz
      - ln -s apache-maven-3.9.5 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - mvn test
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
  post_build:
    commands:
      - mvn package
      - mv target/homey-0.0.1.jar homey-0.0.1.jar
artifacts:
  files:
    - '**/*'